# This workflow will check the previous day's weather and alert about watering

name: rain check

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run:
          echo 'text text text'
